hiroxto/utils.hiroxto.net

LICENSE

Create license file.
Use MIT License.

Create license file.

---

nuxt.config.ts

Use hard-source-webpack-plugin in build.

Use hard-source-webpack-plugin in build.

---

components/pages/train-number-calc/NumberCalc.vue
lib/TrainNumberCalc.ts
types/index.d.ts

`NumberCalc`コンポーネントで行っている種別計算を、`TrainNumberCalc`クラスに移動。
種別計算は全部`TrainNumberCalc`で行う。

TrainNumberCalcクラスを作成

---

.dockerignore
Dockerfile
README.md
docker-compose.yml

開発向けにDocker と Docker Compose を導入。
~~当面は`node:13.2.0-alpine`を使用。~~
当面はLTSの`node:12.13.1-alpine`を使用。

Docker と Docker Compose を導入

---

netlify.toml

`netlify.toml` を作成。
ビルド構成等は全て`netlify.toml`で管理するように変更。

`netlify.toml` を作成

---

renovate.json

Renovate の設定を修正.
`pin` の設定の追加と, `lockFileMaintenance` の自動マージを有効化.
`renovate.json` ファイルを編集.
なし
なし
なし

Renovate の設定を修正

---

.github/workflows/main.yml
netlify.toml

使用する Node.js のバージョンを 12.18.1 に更新.
GitHub Actions と Netlify の設定ファイルを修正.
なし
なし
なし

使用する Node.js のバージョンを 12.18.1 に更新.

---

Dockerfile

Dockerに必要なパッケージをインストール

---

components/pages/train-number-calc/HowToCalc.vue
components/pages/train-number-calc/NumberCalc.vue
pages/cl-sound/index.vue
pages/train-number-calc/index.vue

いくつかのHTML構造を変更．
コンテンツ部分をcontentで囲むようにした．

いくつかのHTML構造を変更

---

package.json
yarn.lock

qrcode.vueのバージョンを修正

---

.github/workflows/main.yml

Dockerでのテストを追加

---

.github/workflows/main.yml
Dockerfile
netlify.toml

Nodeのバージョンを14.17.4に更新

---

nuxt.config.ts

使用する型をNuxtConfigに変更

---

components/pages/qr-code/BackGroundField.vue
components/pages/qr-code/ErrorCorrectionLevelField.vue
components/pages/qr-code/ForeGroundField.vue
components/pages/qr-code/RenderAsField.vue
components/pages/qr-code/SizeField.vue
components/pages/qr-code/ValueField.vue

computed()に型を追加

---

components/layouts/PageFooter.vue
components/pages/qr-code/ErrorCorrectionLevelField.vue
components/pages/qr-code/RenderAsField.vue
components/pages/qr-code/SizeField.vue
components/pages/train-number-calc/HowToCalc.vue
pages/cl-sound/index.vue
pages/index.vue
pages/qr-code/index.vue
pages/train-number-calc/index.vue
pages/train-number/2018-03-17.vue
pages/train-number/2019-03-16.vue
pages/train-number/index.vue

変数の定義方法を変更．
プリミティブ型は`ref()`，非プリミティブ型は`reactive()`で定義するようにした．

変数の定義方法を変更

---

components/pages/cl-sound/PlaySound.vue
components/pages/cl-sound/Specification.vue

コンタクトレスのサウンドページを拡充．
- 再生ボタンの名前を仕様書通りに変更．
- Alert Toneの再生を実装

コンタクトレスのサウンドページを拡充

---

components/pages/qr-code/ErrorCorrectionLevelField.vue
components/pages/qr-code/RenderAsField.vue

フィールドの書き方を変更
b-fieldでラベルを指定して，div.fieldを削除

フィールドの書き方を変更

---

.github/workflows/main.yml
Dockerfile
netlify.toml

Node.jsのバージョンを16.19.1に更新

---

lib/fare-ticket-route/formatter/default-formatter.ts
pages/fare-ticket-route/index.vue
types/fare-ticket-route.d.ts
types/index.d.ts

経路のフォーマッターを別クラスに分割

---

pages/fare-ticket-route/index.vue

設定ボタンを右側に全て集約

---

package.json
yarn.lock

node-sassを削除

---

pages/fare-ticket-route/index.vue

逆向きボタンを発着逆転に変更

---

components/pages/qr-code/BackGroundField.vue
components/pages/qr-code/ErrorCorrectionLevelField.vue
components/pages/qr-code/ForeGroundField.vue
components/pages/qr-code/RenderAsField.vue
components/pages/qr-code/SizeField.vue
components/pages/qr-code/ValueField.vue
nuxt.config.ts
package.json
pages/qr-code/index.vue
store/qrCodeGenerator.ts
tsconfig.json
types/state.d.ts
yarn.lock

VuexをPiniaに移行

---

components/layouts/PageFooter.vue
pages/epgs/recorded-name.vue
pages/index.vue

録画サーバーの保存先ディレクトリ名を生成するツールを作成した。
ついでに保存先ルールを書いた。

録画サーバーの保存先ディレクトリ名を生成するツールを作成

---

.github/workflows/main.yml
Dockerfile
docker-compose.yml

Dockerで利用するポートを3000に変更

---

.github/workflows/main.yml
Dockerfile
netlify.toml

Node.jsをv20.5.0に更新

---

.github/workflows/main.yml

GitHub Actionsの実行タイミングをmasterへのpushと全てのプルリクエストに変更

GitHub Actionsの実行タイミングをmasterへのpushと全てのプルリクエストに変更

---

renovate.json

Renovateでvee-validateをグループ化

---

pages/epgs/recorded-name.vue

シーズンを自動選択する機能を追加

---

README.md
netlify.toml
nuxt.config.ts
public/_redirects

NetlifyからCloudflare Pagesに移行

---

.gitignore
components/layouts/PageFooter.vue
components/pages/qr-code/ErrorCorrectionLevelField.vue
components/pages/qr-code/RenderAsField.vue
components/pages/train-number-calc/NumberCalc.vue
components/ui/LinksMenu.vue
lib/TrainNumberCalc.ts
lib/fare-ticket-route/formatter/default-formatter.ts
lib/fare-ticket-route/formatter/like-mr52-formatter.ts
pages/fare-ticket-route/index.vue
pages/index.vue
pages/train-number/index.vue
store/qrCodeGenerator.ts

型のインポート方法を修正
